flags: {}

# resolver: lts-9.20 # ghc-8.0.2
# resolver: lts-11.12 # ghc-8.2.2
resolver: lts-12.4 # ghc-8.4.3
# resolver: lts-12.19 # ghc-8.4.4

# resolver: nightly-2018-11-23 # ghc-8.6.2

# resolver: lts-14.14 # ghc-8.6.5

extra-deps:
  - semiring-num-1.6.0.3

# When https://github.com/oisdk/semiring-num/pull/2 is merged and released to
# Hackage, switch to it, and re-try GHC 8.4.3 and later.

